-- CREATE DATABASE `final_project`;
-- USE final_project;

-- DROP TABLE IF EXISTS `person`;
-- CREATE TABLE person (
--   `PersonID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
--   `FirstName` VARCHAR(255) NOT NULL DEFAULT '',
--   `LastName` VARCHAR(255) NOT NULL DEFAULT '' ,
--   `Email` VARCHAR(255) NOT NULL DEFAULT '' 
-- );

-- DROP TABLE IF EXISTS `item`;
-- CREATE TABLE item (
--   `ItemID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
--   `Name` VARCHAR(255) NOT NULL DEFAULT ''
-- );

-- DROP TABLE IF EXISTS `order`;
-- CREATE TABLE order (
--   `OrderID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
--   `PersonID` INT UNSIGNED NOT NULL,
--   `OrderDate` DATETIME  ,
--   FOREIGN KEY (PersonID) REFERENCES people (PersonID)
-- );

-- DROP TABLE IF EXISTS `order_details`;
-- CREATE TABLE order_details (
--   `OrderDetailsID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
--   `OrderID` INT UNSIGNED NOT NULL ,
--   `ItemID` INT UNSIGNED NOT NULL ,
--   `Quantity` INT NOT NULL DEFAULT 0,
--   FOREIGN KEY (OrderID) REFERENCES orders (OrderID),
--   FOREIGN KEY (ItemID) REFERENCES items (ItemID)
-- );

