DROP TABLE IF EXISTS `person`;
CREATE TABLE person (
  `personId` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `firstName` VARCHAR(255) NOT NULL DEFAULT '',
  `lastName` VARCHAR(255) NOT NULL DEFAULT '' ,
  `email` VARCHAR(255) NOT NULL DEFAULT '' 
);

DROP TABLE IF EXISTS `item`;
CREATE TABLE item (
  `itemId` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Name` VARCHAR(255) NOT NULL DEFAULT ''
);

DROP TABLE IF EXISTS `orderTable`;
CREATE TABLE orderTable (
  `orderTableId` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `personId` INT UNSIGNED NOT NULL,
  `orderDate` DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (personId) REFERENCES person (personId) on delete cascade
);

DROP TABLE IF EXISTS `orderDetails`;
CREATE TABLE orderDetails (
  `orderDetailsId` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `orderTableId` INT UNSIGNED NOT NULL ,
  `itemId` INT UNSIGNED NOT NULL ,
  `quantity` INT NOT NULL DEFAULT 0,
  FOREIGN KEY (orderTableId) REFERENCES `orderTable` (orderTableId) on delete cascade,
  FOREIGN KEY (itemId) REFERENCES item (itemId) on delete cascade
);

